// Generated by gen_whatsnew.py - do not hand-edit.
// Empty the three arrays to hide the About page link entirely.
const WHATS_NEW = {
 "title": "New Timetable",
 "note": "Houghton have published an updated timetable. Here is what moved.",
 "hideAfter": [
  2026,
  7,
  6,
  23,
  59
 ],
 "retimed": [
  {
   "day": "Thursday",
   "stage": "Derren Smart",
   "name": "Radioactive Man (Live)",
   "was": "22:30–00:30",
   "now": "22:30–00:00"
  },
  {
   "day": "Friday",
   "stage": "Gramophone",
   "name": "Al Wootton (Live)",
   "was": "04:00–05:30",
   "now": "04:00–05:00"
  },
  {
   "day": "Friday",
   "stage": "Pinters",
   "name": "Awkward Moments (Live)",
   "was": "23:00–00:30",
   "now": "23:00–00:00"
  },
  {
   "day": "Friday",
   "stage": "The Armadillo",
   "name": "Baby Vulture & E/Tape",
   "was": "18:00–19:00",
   "now": "18:00–23:00"
  },
  {
   "day": "Friday",
   "stage": "The Orchard",
   "name": "Life Drawing with Sophia Shuvalova",
   "was": "17:00–18:00",
   "now": "17:00–18:30"
  },
  {
   "day": "Saturday",
   "stage": "Derren Smart",
   "name": "Decius Live",
   "was": "02:00–03:30",
   "now": "02:30–03:30"
  },
  {
   "day": "Saturday",
   "stage": "Derren Smart",
   "name": "Craig Richards",
   "was": "22:30–02:00",
   "now": "22:30–02:30"
  },
  {
   "day": "Saturday",
   "stage": "Gramophone",
   "name": "Nidia",
   "was": "03:00–08:00",
   "now": "03:00–05:00"
  },
  {
   "day": "Saturday",
   "stage": "Outburst",
   "name": "Konduku",
   "was": "19:00–22:00",
   "now": "20:00–23:00"
  },
  {
   "day": "Saturday",
   "stage": "The Orchard",
   "name": "Life Drawing with Sophia Shuvalova",
   "was": "18:00–18:30",
   "now": "17:30–19:00"
  },
  {
   "day": "Saturday",
   "stage": "Warehouse",
   "name": "Slam (Live)",
   "was": "01:30–03:00",
   "now": "01:30–02:30"
  },
  {
   "day": "Saturday",
   "stage": "Warehouse",
   "name": "Quest",
   "was": "03:00–05:00",
   "now": "02:30–05:00"
  },
  {
   "day": "Sunday",
   "stage": "Earthling",
   "name": "OK Williams",
   "was": "23:00–01:00",
   "now": "21:00–23:00"
  },
  {
   "day": "Sunday",
   "stage": "Earthling",
   "name": "Batu",
   "was": "21:00–23:00",
   "now": "23:00–01:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Talk: Chez Damier",
   "was": "12:00–12:30",
   "now": "12:00–13:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Talk: Digging Deep",
   "was": "12:30–13:30",
   "now": "13:00–14:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Dominic Capello",
   "was": "13:30–14:30",
   "now": "14:00–15:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Talk: The Sound of Psychedelics",
   "was": "14:30–15:00",
   "now": "15:00–16:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Chez De Milo",
   "was": "15:30–16:30",
   "now": "16:00–17:00"
  },
  {
   "day": "Sunday",
   "stage": "The Armadillo",
   "name": "Facta & K-Lone",
   "was": "16:30–20:00",
   "now": "17:00–20:00"
  },
  {
   "day": "Sunday",
   "stage": "The Orchard",
   "name": "Soundbath with Veronika",
   "was": "12:00–12:30",
   "now": "12:00–13:00"
  },
  {
   "day": "Sunday",
   "stage": "The Orchard",
   "name": "Tom Pardhy Life Celebration",
   "was": "13:00–14:00",
   "now": "13:30–14:30"
  },
  {
   "day": "Sunday",
   "stage": "The Orchard",
   "name": "TBC",
   "was": "14:30–15:30",
   "now": "15:00–16:00"
  },
  {
   "day": "Sunday",
   "stage": "The Orchard",
   "name": "Life Drawing with Sophia Shuvalova",
   "was": "16:00–17:00",
   "now": "16:30–17:30"
  },
  {
   "day": "Sunday",
   "stage": "The Orchard",
   "name": "Breathwork Breath to Restore",
   "was": "17:30–19:00",
   "now": "18:00–19:30"
  }
 ],
 "added": [
  {
   "day": "Friday",
   "stage": "Pinters",
   "name": "Awkward Moments (Ambient Live)",
   "time": "13:00–14:00"
  },
  {
   "day": "Saturday",
   "stage": "Outburst",
   "name": ".VRIL (Live)",
   "time": "19:00–20:00"
  }
 ],
 "removed": [
  {
   "day": "Friday",
   "stage": "Pinters",
   "name": "Maguire (Live)",
   "time": "13:00–14:00"
  },
  {
   "day": "Saturday",
   "stage": "Outburst",
   "name": "Peverelist",
   "time": "22:00–23:00"
  }
 ]
};
